* Introduction

  *rogueui* is a mod for the game [[https://www.kleientertainment.com/games/invisible-inc][Invisible, Inc.]], a turn-based
   tactical stealth game in the world of espionage, with a rogue-like
   component.

   The sole focus of this mod is on the user-interface, which is
   stream-lined in various ways:

   + disable \"I am ready\" screen
   + disable intro video
   + disable first alarm tip pop-up
   + disable mission start confirmation
   + disable mission objectives pop-up
   + disable mission dialog pop-ups
   + disable agency screen voice-over
   + disable all in-game voice-over
   + disable map scripts
   + remember selected agency

   These features may be enabled or disabled in the in-game options
   menu.

* Install

  If you're paranoid, first create a backup of your game's folder.
  Though no files should be overridden by the installation.

** Unix like

   Run /make/ in the root directory and extract the created tar from
   the dist directory into the game's root-directory. 

   A 5th tab named *ROGUEUI* should appear in the game's option menu.

** Other 

   1. Create a zip archive named /scripts.zip/ containing the
      following files from the mod's root directory:

      - rogueui.lua
      - modinit.lua

   2. Create the path $INVISIBLE/game/dlc/rogueui/, whereby
      $INVISIBLE should be the game's install directory.

   3. Move the zip archive into this folder.
      
* Uninstall

  Simply remove the directory $INVISIBLE/game/dlc/rogueui .
